alias: Wake Up
description: ''
triggers:
  - trigger: time
    at: 06:00:00
conditions: []
actions:
  - action: calendar.get_events
    metadata: {}
    data:
      duration:
        hours: 10
        minutes: 0
        seconds: 0
    target:
      entity_id: calendar.work
    response_variable: get_events_response
  - condition: template
    value_template: '{{ get_events_response[''calendar.work''].events | count > 0 }}'
  - variables:
      next_work: '{{ get_events_response[''calendar.work''].events.0 }}'
      fade_duration:
        hours: 1
        minutes: 0
        seconds: 0
      after_complete: Turn Off
  - wait_for_trigger:
      - trigger: time
        at: '{{ (next_work.start | as_datetime - timedelta(hours=fade_duration.hours, minutes=fade_duration.minutes, seconds=fade_duration.seconds)).time() }}'
    continue_on_timeout: false
    timeout:
      hours: 10
      minutes: 0
      seconds: 0
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ next_work.location == ''Office'' }}'
        sequence:
          - variables:
              fade_duration:
                hours: 1
                minutes: 0
                seconds: 0
              after_complete: Turn Off
      - conditions:
          - condition: template
            value_template: '{{ next_work.location == ''Home'' }}'
        sequence:
          - variables:
              fade_duration:
                hours: 0
                minutes: 30
                seconds: 0
              after_complete: Working from Home
  - action: light.turn_on
    metadata: {}
    data:
      kelvin: 2000
      brightness_pct: 1
    target:
      area_id: jack_s_bedroom
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
  - parallel:
      - action: script.light_fade
        metadata: {}
        data:
          lampBrightnessScale: zeroToTwoFiftyFive
          easingTypeInput: auto
          endBrightnessPercent: 100
          endBrightnessEntityScale: zeroToOneHundred
          autoCancelThreshold: 10
          shouldStopIfTheLampIsTurnedOffDuringTheFade: true
          shouldResetTheStopEntityToOffAtStart: false
          shouldInvertTheValueOfTheStopEntity: false
          minimumStepDelayInMilliseconds: 100
          shouldTryToUseNativeLampTransitionsToo: true
          isDebugMode: false
          light: light.wiz_rgbw_tunable_2278da
          endColorTemperatureKelvin: 6500
          transitionTime: '{{ fade_duration }}'
      - action: script.light_fade
        metadata: {}
        data:
          lampBrightnessScale: zeroToTwoFiftyFive
          easingTypeInput: auto
          endBrightnessPercent: 100
          endBrightnessEntityScale: zeroToOneHundred
          autoCancelThreshold: 10
          shouldStopIfTheLampIsTurnedOffDuringTheFade: true
          shouldResetTheStopEntityToOffAtStart: false
          shouldInvertTheValueOfTheStopEntity: false
          minimumStepDelayInMilliseconds: 100
          shouldTryToUseNativeLampTransitionsToo: true
          isDebugMode: false
          light: light.wiz_rgbw_tunable_08365a
          endColorTemperatureKelvin: 6500
          transitionTime: '{{ fade_duration }}'
  - wait_for_trigger:
      - trigger: calendar
        entity_id: calendar.work
        event: start
        offset: 0:0:0
    continue_on_timeout: false
    timeout:
      hours: 1
      minutes: 0
      seconds: 0
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ after_complete == ''Turn Off'' }}'
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            target:
              area_id: jack_s_bedroom
      - conditions:
          - condition: template
            value_template: '{{ after_complete == ''Working from Home'' }}'
        sequence:
          - action: scene.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: scene.working_from_home
mode: single
